### PR TITLE
[release v1.10.0] feat: native type streams

### LINKED ISSUE #5: Release v1.10.0
```[tasklist]
- [x] Update `fiber-proto` (`git submodule update --remote fiber-proto`)
- [x] Regenerate and implement the new gRPC bindings (build.sh)
- [x] Implement only the non-deprecated streams
- [x] Use `ethereumjs` for transaction types (always return signer too! recovering it takes too long in JS)
- [x] Use https://github.com/ChainSafe/lodestar to decode SSZ beacon blocks
- [x] For execution payloads, convert to `ethereumjs` blocks
- [x] For transactions and beacon blocks, have a "raw" variant that just returns the RLP / SSZ encoding
- [x] Add `x-client-version` header to all gRPC streams
```

### PR DESCRIPTION
**Pull request by merklefruit**
- work in progress
- closes #5

### CODE REVIEW

**Comment by thedevbirb** [comment]
I think that this is ready for a first round of review. There are some things left:
- [x] ~test remaining "send" functions (`sendRawTransaction`, `send(Raw)TransactionSequence`)~ -- interface has not changed from last release
- [x] there some empty fields in the execution payload header (`nonce`, `transactionsTrie`, `withdrawalRoots`, `parentBeaconBlockRoot`) with some TODOs left by @merklefruit. 
- [x] test this client again the other Fiber client implementations

**Review by mempirate — APPROVED** [review]
Looks good, thanks! Once this is tested in the client tests we can merge and release v1.9.0

**Comment by thedevbirb** [comment]
> Looks good, thanks! Once this is tested in the client tests we can merge and release v1.9.0

Thanks! Yes for client tests I think we should merge https://github.com/chainbound/fiber-e2e-test/pull/8 which can be useful.

**Comment by thedevbirb** [comment]
E2E tests are passing, therefore this is ready! See also https://github.com/chainbound/fiber-e2e-test/pull/9

**Comment by mempirate** [comment]
LGTM! Will publish release

**Pull request merged**
